on:
  push:
    # branches: [main]
    paths-ignore:
      - '*.md'
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build graph's SPA
        uses: logseq/publish-spa@feat/db
        with:
          theme-mode: dark
          accent-color: cyan
          version: 92cc1ce38c08daf9a3ff455d2c2bfab273b98c46

      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
